// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'arn:aws:cognito-idp:us-east-1:112121669279:userpool/us-east-1_AWAiXpTBd',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'rnclonefurgo-hosting-mobilehub-681718598',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd35yy4fazlppjg.cloudfront.net',
    'aws_mobile_analytics_app_id': 'e055b35b729e4cffa330ee007ef71e3b',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '44b82d68-d566-4bee-818f-254c03abd884',
    'aws_project_name': 'RNcloneFurgo',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'rnclonefurgo-mobilehub-681718598',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_AWAiXpTBd',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '771b51020kj6ogvvfus39fak4t',
}

export default awsmobile;
